### ISSUE TITLE
Week numbers continue after end of year in angular-ui datepicker

### ISSUE THREAD

**Issue by annakastet** [Studentmediene/Barteguiden-Web#36]
Updating the datepicker might fix it.

**Comment by martinhath** [comment]
Apparently, it is a known issue: [here](https://github.com/angular-ui/bootstrap/issues/3120) and [here](https://github.com/angular-ui/bootstrap/issues/2506) (the last link is from July 2014). Maybe the best way to fix this (if we really care - it won't really be visible until January next year), is to fork the project, and fix it ourselves. There are some pull requests for the issues linked, but they aren't merged (maybe for a reason? :)

**Comment by Essoen** [comment]
Sounds like a lot of work for a small gain. I suggest to wait and see. Anyone following updatess?

**Comment by andybb** [comment]
I subscribed to some of the pull requests. I suggest we remove the week numbers for now by setting show-weeks to false in the Datepicker settings.
